- name: Install tomcat8 and tomcat8-admin and add a role
  hosts: all
  tasks:
   - name: install tomcat8 and tomcat8-admin
     apt:
      name: "{{ item.a }}" 
      state: present
      update_cache: "{{ item.b }}"
     with_items:
      - { a: tomcat8 , b: yes }
      - { a: tomcat8-admin , b: no }
   - name: Update tomcat8-users.xml file
     lineinfile:
      path: /etc/tomcat8/tomcat-users.xml
      backup: yes
      insertbefore: '</tomcat-users>'
      line: '<user username="intelleq" password="myintelleq" fullName="Administrator" roles="manager-script"/>'
     notify:
      - restart server
  handlers:
   - name: restart server
     service:
      name: tomcat8
      state: restarted
...

